<?php

use App\Http\Controllers\Api\AccountController;
use App\Http\Controllers\Api\Admin\AdminAccountController;
use App\Http\Controllers\Api\Admin\AdminBuilderPortalController;
use App\Http\Controllers\Api\Admin\AdminRentHistoryController;
use App\Http\Controllers\Api\Admin\AdminReviewController;
use App\Http\Controllers\Api\Admin\AdminReferralController;
use App\Http\Controllers\Api\Admin\AdminNriCaseController;
use App\Http\Controllers\Api\Admin\AdminSiteVisitController;
use App\Http\Controllers\Api\Admin\AdminStatsController;
use App\Http\Controllers\Api\Admin\ImageUploadController;
use App\Http\Controllers\Api\Admin\SocietyImportController;
use App\Http\Controllers\Api\Admin\VerifiedSocietyImporterController;
use App\Http\Controllers\Api\AiChatController;
use App\Http\Controllers\Api\AIController;
use App\Http\Controllers\Api\BuilderPortalController;
use App\Http\Controllers\Api\LeadController;
use App\Http\Controllers\Api\PropertyController;
use App\Http\Controllers\Api\RentHistoryController;
use App\Http\Controllers\Api\ReviewController;
use App\Http\Controllers\Api\ReferralController;
use App\Http\Controllers\Api\NriCaseController;
use App\Http\Controllers\Api\SavedSearchController;
use App\Http\Controllers\Api\SiteVisitController;
use App\Http\Controllers\Api\SocietyController;
use Illuminate\Support\Facades\Route;

Route::get('/health', fn () => response()->json([
    'status' => 'ok',
    'service' => 'societyflats-api',
]));

Route::get('/societies', [SocietyController::class, 'index']);
Route::get('/societies/{idOrSlug}/google-place-photo', [SocietyController::class, 'googlePlacePhoto']);
Route::get('/societies/{slug}', [SocietyController::class, 'show']);
Route::get('/properties', [PropertyController::class, 'index']);
Route::get('/properties/{idOrSlug}', [PropertyController::class, 'show']);
Route::post('/leads', [LeadController::class, 'store'])->middleware('throttle:10,1');
Route::post('/nri-cases', [NriCaseController::class, 'store'])->middleware('throttle:5,1');
Route::post('/ai/advisor', [AIController::class, 'advisor']);
Route::post('/ai/chat', [AiChatController::class, 'store'])->middleware('throttle:10,1');
Route::get('/ai/chat/{token}', [AiChatController::class, 'show'])->middleware('throttle:30,1');
Route::post('/ai/recommendations', [AIController::class, 'recommendations']);
Route::get('/ai/rent-estimate', [AIController::class, 'rentEstimate']);
Route::get('/societies/{idOrSlug}/reviews', [ReviewController::class, 'bySociety']);
Route::get('/societies/{idOrSlug}/rent-history', [RentHistoryController::class, 'bySociety']);
Route::get('/societies/{idOrSlug}/announcements', [BuilderPortalController::class, 'announcements']);
Route::get('/rent-intelligence/trends', [RentHistoryController::class, 'trends']);
Route::post('/reviews', [ReviewController::class, 'store']);
Route::post('/reviews/{review}/helpful', [ReviewController::class, 'markHelpful']);
Route::get('/site-visits/{token}', [SiteVisitController::class, 'show']);
Route::post('/site-visits/{token}/confirm', [SiteVisitController::class, 'confirm']);
Route::prefix('admin')->middleware('admin.api')->group(function () {
    Route::get('/stats', AdminStatsController::class);
    Route::post('/uploads/images', [ImageUploadController::class, 'store']);
    Route::post('/societies/fetch-from-url', [SocietyController::class, 'fetchFromUrl']);
    Route::post('/societies/fetch-from-brochure', [SocietyController::class, 'fetchFromBrochure']);
    Route::post('/societies/create-from-fetched-data', [SocietyController::class, 'createFromFetchedData']);
    Route::post('/societies/{society}/enrich', [SocietyController::class, 'enrich']);
    Route::post('/societies/publish-fields/backfill', [SocietyController::class, 'backfillPublishFields']);
    Route::post('/societies/google-places-image-references/bulk', [SocietyController::class, 'bulkGooglePlacesImageReferences']);
    Route::post('/societies/{society}/google-places-image-reference', [SocietyController::class, 'googlePlacesImageReference']);
    Route::get('/import/jobs', [SocietyImportController::class, 'jobs']);
    Route::get('/import/jobs/{job}', [SocietyImportController::class, 'show']);
    Route::delete('/import/jobs/{job}', [SocietyImportController::class, 'destroy']);
    Route::get('/import/ai-status', [SocietyImportController::class, 'aiStatus']);
    Route::get('/import/place-photo', [SocietyImportController::class, 'placePhoto']);
    Route::post('/import/single', [SocietyImportController::class, 'single']);
    Route::post('/import/bulk', [SocietyImportController::class, 'bulk']);
    Route::post('/import/spreadsheet', [SocietyImportController::class, 'spreadsheet']);
    Route::post('/import/structured', [SocietyImportController::class, 'structuredImport']);
    Route::post('/import/societies/bulk-re-enrich', [SocietyImportController::class, 'bulkReEnrich']);
    Route::patch('/import/societies/{society}/image', [SocietyImportController::class, 'imageDecision']);
    Route::post('/import/societies/{society}/image-candidates', [SocietyImportController::class, 'imageCandidateDecision']);
    Route::post('/import/societies/{society}/re-enrich', [SocietyImportController::class, 'reEnrich']);
    Route::post('/import/societies/{society}/market-refresh', [SocietyImportController::class, 'marketRefresh']);
    Route::post('/import/societies/{society}/publish', [SocietyImportController::class, 'publish']);
    Route::prefix('verified-importer')->group(function () {
        Route::get('/jobs', [VerifiedSocietyImporterController::class, 'jobs']);
        Route::get('/jobs/{job}', [VerifiedSocietyImporterController::class, 'showJob']);
        Route::post('/single', [VerifiedSocietyImporterController::class, 'singleImport']);
        Route::post('/bulk', [VerifiedSocietyImporterController::class, 'bulkImport']);
        Route::post('/excel/preview', [VerifiedSocietyImporterController::class, 'previewExcel']);
        Route::post('/excel/import', [VerifiedSocietyImporterController::class, 'importExcel']);
        Route::get('/template', [VerifiedSocietyImporterController::class, 'downloadTemplate']);
        Route::get('/review', [VerifiedSocietyImporterController::class, 'reviewQueue']);
        Route::post('/fields/{field}/approve', [VerifiedSocietyImporterController::class, 'approveField']);
        Route::post('/fields/{field}/reject', [VerifiedSocietyImporterController::class, 'rejectField']);
        Route::post('/images/{image}/approve', [VerifiedSocietyImporterController::class, 'approveImage']);
        Route::post('/images/{image}/reject', [VerifiedSocietyImporterController::class, 'rejectImage']);
        Route::post('/images/{image}/set-cover', [VerifiedSocietyImporterController::class, 'setCoverImage']);
        Route::post('/jobs/{job}/retry-failed', [VerifiedSocietyImporterController::class, 'retryFailedRows']);
        Route::post('/societies/{society}/apply-high-confidence', [VerifiedSocietyImporterController::class, 'applyHighConfidence']);
        Route::post('/societies/{society}/enrich-google', [VerifiedSocietyImporterController::class, 'enrichExistingDraft']);
        Route::post('/societies/{society}/source-layers/{layer}', [VerifiedSocietyImporterController::class, 'importSourceLayer']);
        Route::post('/societies/{society}/generate-description', [VerifiedSocietyImporterController::class, 'generateDescription']);
        Route::post('/societies/{society}/generate-seo', [VerifiedSocietyImporterController::class, 'generateSeo']);
        Route::post('/societies/{society}/generate-scores', [VerifiedSocietyImporterController::class, 'generateScores']);
        Route::post('/societies/{society}/apply-market-data', [VerifiedSocietyImporterController::class, 'applyMarketData']);
    });
    Route::post('/societies/nearby-intelligence/bulk-auto-fill', [SocietyController::class, 'bulkNearbyIntelligenceAutoFill']);
    Route::post('/societies/{society}/nearby-intelligence/auto-fill', [SocietyController::class, 'nearbyIntelligenceAutoFill']);
    Route::apiResource('societies', SocietyController::class)->except(['create', 'edit']);
    Route::apiResource('properties', PropertyController::class)->except(['create', 'edit']);
    Route::apiResource('leads', LeadController::class)->only(['index', 'show', 'update', 'destroy']);
    Route::apiResource('accounts', AdminAccountController::class)->only(['index', 'show', 'update']);
    Route::apiResource('reviews', AdminReviewController::class)->only(['index', 'update', 'destroy']);
    Route::apiResource('referrals', AdminReferralController::class)->only(['index', 'update']);
    Route::apiResource('nri-cases', AdminNriCaseController::class)->only(['index', 'update']);
    Route::apiResource('rent-history', AdminRentHistoryController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::get('/builder-claims', [AdminBuilderPortalController::class, 'claims']);
    Route::patch('/builder-claims/{claim}', [AdminBuilderPortalController::class, 'updateClaim']);
    Route::get('/society-announcements', [AdminBuilderPortalController::class, 'announcements']);
    Route::patch('/society-announcements/{announcement}', [AdminBuilderPortalController::class, 'updateAnnouncement']);
    Route::get('/review-responses', [AdminBuilderPortalController::class, 'reviewResponses']);
    Route::patch('/review-responses/{response}', [AdminBuilderPortalController::class, 'updateReviewResponse']);
    Route::post('/site-visits/{siteVisit}/remind', [AdminSiteVisitController::class, 'remind']);
    Route::apiResource('site-visits', AdminSiteVisitController::class)->only(['index', 'store', 'update']);
});

Route::prefix('accounts')->group(function () {
    Route::post('/upsert', [AccountController::class, 'upsert']);
    Route::post('/request-otp', [AccountController::class, 'requestOtp'])->middleware('throttle:5,1');
    Route::post('/verify-otp', [AccountController::class, 'verifyOtp'])->middleware('throttle:10,1');
    Route::get('/me', [AccountController::class, 'me']);
    Route::get('/dashboard', [AccountController::class, 'dashboard']);
    Route::get('/referrals', [ReferralController::class, 'index']);
    Route::post('/referrals', [ReferralController::class, 'store'])->middleware('throttle:10,1');
    Route::apiResource('saved-searches', SavedSearchController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::get('/saved-search-alerts', [SavedSearchController::class, 'alerts']);
    Route::get('/builder-claims', [BuilderPortalController::class, 'claims']);
    Route::post('/builder-claims', [BuilderPortalController::class, 'storeClaim']);
    Route::post('/builder-claims/{claim}/announcements', [BuilderPortalController::class, 'storeAnnouncement']);
    Route::post('/builder-claims/{claim}/reviews/{review}/response', [BuilderPortalController::class, 'storeReviewResponse']);
});
