import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, Database, FileSpreadsheet, Images, ListChecks, RefreshCw, ShieldCheck, Upload } from "lucide-react";
import { AdminLayout } from "@/layouts/AdminLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { VerifiedImportImageCard, type VerifiedImportImage } from "@/components/admin/VerifiedImportImageCard";
import {
  applyVerifiedHighConfidenceFields, approveVerifiedImportField, approveVerifiedImportImage, confirmVerifiedExcelImport,
  createBulkVerifiedImport, createSingleVerifiedImport, downloadVerifiedImportTemplate,
  enrichExistingVerifiedSocietyDraft,
  generateVerifiedSocietyDescription, generateVerifiedSocietyScores, generateVerifiedSocietySeo,
  importVerifiedSocietySourceLayer, importVerifiedSocietyGoogleNearby,
  getVerifiedImporterJobs, getVerifiedReviewQueue, previewVerifiedExcelImport,
  rejectVerifiedImportField, rejectVerifiedImportImage, retryVerifiedImportFailedRows,
  setVerifiedImportCoverImage,
} from "@/lib/verifiedImporterApi";

type Tab = "single" | "bulk" | "excel" | "jobs" | "review";
type Job = { id:number; job_type:string; status:string; total_rows:number; processed_rows:number; created_societies_count:number; skipped_count:number; failed_count:number; overall_confidence?:number; created_at?:string };
type Field = { id:number; society_id:number; field_name:string; normalized_value?:string; source_type:string; confidence_score?:number };
type Image = VerifiedImportImage;
type Review = { societies:any[]; fields:Field[]; images:Image[]; duplicates:any[]; low_confidence:any[] };
type SourceLayer = "rera" | "builder" | "nearby" | "market";

const tabs: Array<{id:Tab;label:string;icon:any}> = [
  {id:"single",label:"Single Import",icon:ShieldCheck},{id:"bulk",label:"Bulk Import",icon:ListChecks},
  {id:"excel",label:"Excel Import",icon:FileSpreadsheet},{id:"jobs",label:"Import Jobs",icon:Database},{id:"review",label:"Review Queue",icon:Images},
];
const amenityOptions = ["Clubhouse","Swimming Pool","Gym","Kids Play Area","Tennis Court","Badminton Court","Basketball Court","Jogging Track","Power Backup","Visitor Parking","Pet Friendly","24x7 Security","Concierge","CCTV","Landscaped Greens","Senior Citizen Area"];
const longFields = new Set(["description","nearby_schools","nearby_metro","nearby_hospitals","nearby_office_hubs","meta_description","gallery_image_urls","notes"]);
const advancedFields = new Set(["legal_name","rera_number","rera_url","promoter_name","rera_status","registration_validity","certificate_url","description","rent_min","rent_max","rent_range","buy_min","buy_max","resale_min","resale_max","buy_range","average_rent","average_sale_price","price_per_sqft","rental_yield","maintenance_charges","market_notes","score","security_score","maintenance_score","connectivity_score","lifestyle_score","investment_score","meta_title","meta_description","official_project_url","developer_url","rera_search_url","brochure_url","cover_image_url","gallery_image_urls","image_reference_url","notes"]);
const layerLabels:Record<string,string>={google:"Google Location Layer",rera:"RERA / Legal Layer",builder:"Builder / Brochure Layer",nearby:"Nearby Places Layer",market:"Market Layer",content:"Content / SEO Layer",images:"Images Layer"};
const layerFields:Record<SourceLayer,string[]>={
  rera:["rera_number","rera_url","legal_name","promoter_name","rera_status","registration_date","registration_validity","certificate_url","oc_cc_pcc_url","source_url","notes"],
  builder:["builder_name","builder_url","official_project_url","brochure_url","project_status","possession_status","possession_date","configurations","land_area","tower_count","unit_count","amenities","description_source_text","cover_image_url","gallery_image_urls","notes"],
  nearby:["nearby_schools","nearby_hospitals","nearby_metro","office_hubs","nearby_malls","nearby_markets","commute_notes","source_url","notes"],
  market:["rent_min","rent_max","rent_range","buy_min","buy_max","resale_min","resale_max","buy_range","average_rent","average_sale_price","price_per_sqft","rental_yield","maintenance_charges","market_notes","market_source_url","market_source_type","confidence_score","notes"],
};
const layerLongFields=new Set(["notes","amenities","description_source_text","gallery_image_urls","nearby_schools","nearby_hospitals","nearby_metro","office_hubs","nearby_malls","nearby_markets","commute_notes","market_notes"]);
const initialSingle = {
  name:"", slug:"", builder_name:"", legal_name:"", description:"", city:"Gurugram", state:"Haryana", sector:"", locality:"", address:"",
  rera_number:"", rera_url:"", promoter_name:"", rera_status:"", registration_validity:"", certificate_url:"",
  google_maps_url:"", latitude:"", longitude:"", score:"", security_score:"", maintenance_score:"", connectivity_score:"", lifestyle_score:"", investment_score:"",
  rent_min:"", rent_max:"", rent_range:"", buy_min:"", buy_max:"", resale_min:"", resale_max:"", buy_range:"", average_rent:"", average_sale_price:"", price_per_sqft:"", rental_yield:"", maintenance_charges:"", market_notes:"", amenities:[] as string[],
  nearby_schools:"", nearby_metro:"", nearby_hospitals:"", nearby_office_hubs:"", official_project_url:"", developer_url:"", rera_search_url:"",
  meta_title:"", meta_description:"", google_place_id:"", brochure_url:"", cover_image_url:"", gallery_image_urls:"", image_reference_url:"", notes:"", duplicate_action:"skip",
};

function Confidence({value=0}:{value?:number}) { const tone=value>=90?"bg-emerald-100 text-emerald-700":value>=70?"bg-amber-100 text-amber-700":"bg-rose-100 text-rose-700"; return <span className={`rounded-full px-2.5 py-1 text-xs font-black ${tone}`}>{value}%</span>; }

export function AdminVerifiedSocietyImporterPage() {
  const [tab,setTab]=useState<Tab>("single"); const [single,setSingle]=useState(initialSingle); const [bulk,setBulk]=useState("");
  const [jobs,setJobs]=useState<Job[]>([]); const [review,setReview]=useState<Review>({societies:[],fields:[],images:[],duplicates:[],low_confidence:[]});
  const [preview,setPreview]=useState<any>(null); const [lastJob,setLastJob]=useState<any>(null); const [fileName,setFileName]=useState(""); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(""); const [error,setError]=useState("");
  const [layerEditor,setLayerEditor]=useState<{society:any;layer:SourceLayer}|null>(null); const [layerValues,setLayerValues]=useState<Record<string,string>>({});

  async function loadJobs(){try{const r=await getVerifiedImporterJobs();setJobs(r?.data?.data||[]);}catch(e){setError(e instanceof Error?e.message:"Could not load jobs.");}}
  async function loadReview(){try{const r=await getVerifiedReviewQueue();setReview(r?.data||{societies:[],fields:[],images:[],duplicates:[],low_confidence:[]});}catch(e){setError(e instanceof Error?e.message:"Could not load review queue.");}}
  useEffect(()=>{void loadJobs();void loadReview();},[]);
  async function run(action:()=>Promise<any>,success:string){try{setBusy(true);setError("");setNotice("");const r=await action();if(r?.data?.id&&r?.data?.job_type)setLastJob(r.data);setNotice(r?.message||success);await Promise.all([loadJobs(),loadReview()]);return r;}catch(e){setError(e instanceof Error?e.message:"Request failed.");}finally{setBusy(false);}}
  const createdSocietyId=lastJob?.rows?.find((row:any)=>row.created_society_id)?.created_society_id;
  const singleEntries=Object.entries(single).filter(([key])=>key!=="duplicate_action"&&key!=="amenities");
  const renderSingleField=([key,value]:[string,unknown])=><label key={key} className={`text-sm font-semibold text-slate-700 ${longFields.has(key)?"md:col-span-2":""}`}>{key.replace(/_/g," ")}{key==="name"?" *":""}{longFields.has(key)?<textarea className="mt-1 min-h-24 w-full rounded-md border border-slate-200 px-3 py-2 font-normal" value={String(value)} onChange={e=>setSingle({...single,[key]:e.target.value})}/>:<Input className="mt-1" value={String(value)} onChange={e=>setSingle({...single,[key]:e.target.value})} />}</label>;
  const amenityFields=<div className="mt-6"><h3 className="font-black text-slate-900">Amenities</h3><p className="mt-1 text-xs text-slate-500">Selected amenities remain source-tracked and need admin review.</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{amenityOptions.map(amenity=><label key={amenity} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-semibold text-slate-700"><input type="checkbox" checked={single.amenities.includes(amenity)} onChange={e=>setSingle({...single,amenities:e.target.checked?[...single.amenities,amenity]:single.amenities.filter(item=>item!==amenity)})}/>{amenity}</label>)}</div></div>;
  const openLayerEditor=(society:any,layer:SourceLayer)=>{setLayerEditor({society,layer});setLayerValues(layer==="market"?{market_source_type:"manual_admin"}:{});setError("");setNotice("");};
  const layerActionLabel=(layer:SourceLayer)=>({rera:"Import RERA / Legal Data",builder:"Import Builder / Brochure Data",nearby:"Import Nearby Places",market:"Import / Apply Market Data"}[layer]);
  const renderLayerCards=(society:any)=><div className="mt-4 grid gap-2 sm:grid-cols-2">{Object.entries(layerLabels).map(([id,label])=>{const info=society.layers?.[id]||{};const nearby=info.details||{};return <div key={id} className="rounded-xl border border-slate-200 bg-slate-50 p-3"><p className="text-xs font-black text-slate-800">{label}</p><p className="mt-1 text-[11px] text-slate-500">{info.completed_fields||0}/{info.total_fields||0} fields · {info.pending_fields||0} pending · {info.confidence?`${info.confidence}% confidence`:"No source yet"}</p>{id==="nearby"?<p className="mt-2 text-[11px] leading-5 text-slate-600">Schools {nearby.schools||0} · Hospitals {nearby.hospitals||0} · Metro {nearby.metro||0} · Offices {nearby.office_hubs||0} · Markets/Malls {nearby.markets_malls||0}<br/>{nearby.source?`${String(nearby.source).replace(/_/g," ")} · ${nearby.last_fetched?new Date(nearby.last_fetched).toLocaleString():"saved"}`:"No nearby source yet"}</p>:null}{id==="market"?<p className="mt-2 text-[11px] font-bold text-amber-700">{info.badge||"Market estimate — needs review"}</p>:null}<div className="mt-2 flex flex-wrap gap-2">{id==="google"?<button className="text-[11px] font-black text-indigo-700" onClick={()=>void run(()=>enrichExistingVerifiedSocietyDraft(society.id),"Existing draft enriched with Google Places.")}>Enrich Google</button>:null}{(["rera","builder","nearby","market"] as string[]).includes(id)?<button className="text-[11px] font-black text-blue-700" onClick={()=>openLayerEditor(society,id as SourceLayer)}>{layerActionLabel(id as SourceLayer)}</button>:null}{id==="nearby"?<button className="text-[11px] font-black text-indigo-700" onClick={()=>void run(()=>importVerifiedSocietyGoogleNearby(society.id),"Google Nearby places imported for review.")}>Fetch Google Nearby</button>:null}{id==="content"?<><button className="text-[11px] font-black text-blue-700" onClick={()=>void run(()=>generateVerifiedSocietyDescription(society.id,true),"Description refreshed for review.")}>Refresh Description</button><button className="text-[11px] font-black text-blue-700" onClick={()=>void run(()=>generateVerifiedSocietySeo(society.id,true),"SEO refreshed for review.")}>Refresh SEO</button><button className="text-[11px] font-black text-blue-700" onClick={()=>void run(()=>generateVerifiedSocietyScores(society.id,true),"Draft scores generated for review.")}>Refresh Draft Scores</button></>:null}<a className="text-[11px] font-black text-slate-600" href={`/admin/societies/${society.id}/edit`}>Open draft</a></div></div>})}</div>;
  const layerEditorPanel=layerEditor?<section className="rounded-[28px] border border-blue-200 bg-blue-50 p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-blue-600">{layerLabels[layerEditor.layer]}</p><h2 className="text-xl font-black">{layerEditor.society.name}</h2><p className="mt-1 text-sm text-blue-800">Only source-backed values will be applied. Every field remains review-required.</p></div><button className="text-sm font-black text-slate-600" onClick={()=>setLayerEditor(null)}>Close</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{layerFields[layerEditor.layer].map(field=><label key={field} className={`text-sm font-semibold text-slate-700 ${layerLongFields.has(field)?"md:col-span-2":""}`}>{field.replace(/_/g," ")}{layerLongFields.has(field)?<textarea className="mt-1 min-h-24 w-full rounded-md border border-blue-200 bg-white px-3 py-2 font-normal" value={layerValues[field]||""} onChange={e=>setLayerValues({...layerValues,[field]:e.target.value})}/>:<Input className="mt-1 bg-white" value={layerValues[field]||""} onChange={e=>setLayerValues({...layerValues,[field]:e.target.value})}/>}</label>)}</div><div className="mt-5 flex gap-3"><Button disabled={busy} className="bg-blue-700" onClick={()=>void (async()=>{const result=await run(()=>importVerifiedSocietySourceLayer(layerEditor.society.id,layerEditor.layer,layerValues),`${layerActionLabel(layerEditor.layer)} completed.`);if(result)setLayerEditor(null);})()}>{layerActionLabel(layerEditor.layer)}</Button><a href={`/admin/societies/${layerEditor.society.id}/edit`} className="inline-flex items-center rounded-xl border border-blue-200 bg-white px-4 text-sm font-black text-blue-700">Open Society Draft</a></div></section>:null;
  const approveQueueCover=(image:Image)=>{const society=review.societies.find(item=>item.id===image.society_id);const replace=Boolean(society?.has_approved_cover)&&window.confirm("An approved cover already exists. Replace it with this candidate?");if(society?.has_approved_cover&&!replace)return;void run(()=>setVerifiedImportCoverImage(image.id,replace),"Cover selected. Society remains unpublished.");};

  return <AdminLayout title="Verified Society Importer" subtitle="Accuracy-first importer for RERA, Google Places, builder data, Excel and image review.">
    <div className="mb-5 flex flex-wrap gap-2">{["Draft only","Admin review required","Existing importer untouched"].map(x=><span key={x} className="rounded-full border border-blue-100 bg-blue-50 px-3 py-1.5 text-xs font-black text-blue-700">{x}</span>)}</div>
    <div className="mb-5 flex flex-wrap gap-2 rounded-[24px] border border-slate-200 bg-white p-2">{tabs.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setTab(id)} className={`flex items-center gap-2 rounded-2xl px-4 py-2.5 text-sm font-bold ${tab===id?"bg-blue-700 text-white":"text-slate-600 hover:bg-slate-50"}`}><Icon className="h-4 w-4" />{label}</button>)}</div>
    {notice?<div className="mb-4 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{notice}</div>:null}{error?<div className="mb-4 flex gap-2 rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-700"><AlertTriangle className="h-4 w-4" />{error}</div>:null}
    {lastJob?<div className="mb-5 rounded-[24px] border border-blue-100 bg-blue-50 p-5"><div className="grid gap-3 sm:grid-cols-6"><div><p className="text-xs font-bold uppercase text-blue-500">Job</p><p className="font-black">#{lastJob.id}</p></div><div><p className="text-xs font-bold uppercase text-blue-500">Status</p><p className="font-black">{lastJob.status}</p></div><div><p className="text-xs font-bold uppercase text-blue-500">Drafts</p><p className="font-black">{lastJob.created_societies_count||0}</p></div><div><p className="text-xs font-bold uppercase text-blue-500">Fields applied</p><p className="font-black">{lastJob.summary?.applied_fields||0}</p></div><div><p className="text-xs font-bold uppercase text-blue-500">Pending fields</p><p className="font-black">{lastJob.summary?.pending_fields||0}</p></div><div><p className="text-xs font-bold uppercase text-blue-500">Pending images</p><p className="font-black">{lastJob.summary?.pending_images||0}</p></div></div><p className="mt-3 text-xs font-bold uppercase text-blue-600">Duplicate status: {lastJob.summary?.duplicate_status||"none"}</p>{createdSocietyId?<a href={`/admin/societies/${createdSocietyId}/edit`} className="mt-4 inline-flex rounded-xl bg-blue-700 px-4 py-2 text-sm font-black text-white">Open Society Draft</a>:null}</div>:null}

    {tab==="single"?<section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Single verified import</h2><p className="mt-1 text-sm text-slate-500">Create a source-tracked draft. Advanced RERA, market, amenity and SEO fields stay review-pending.</p><div className="mt-4 grid gap-3 rounded-2xl bg-blue-50 p-4 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase text-blue-500">Status</p><p className="font-black text-blue-900">Draft</p></div><div><p className="text-xs font-bold uppercase text-blue-500">Verification status</p><p className="font-black text-blue-900">Needs Review</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2">{singleEntries.filter(([key])=>!advancedFields.has(key)).map(renderSingleField)}</div><details className="mt-6 rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black text-slate-800">Advanced RERA, amenities, market, scores and SEO</summary><p className="mt-2 text-xs text-slate-500">Only enter source-backed values. Every value is recorded for admin review.</p><div className="mt-4 grid gap-4 md:grid-cols-2">{singleEntries.filter(([key])=>advancedFields.has(key)).map(renderSingleField)}</div>{amenityFields}</details><p className="mt-5 rounded-2xl bg-slate-50 p-4 text-xs font-semibold text-slate-600">Coordinates, Google Maps status, school/hospital counts, metro notes and office-hub proximity are calculated in the society checklist from the location and nearby-intelligence fields above.</p><label className="mt-5 block text-sm font-semibold">Duplicate action<select className="mt-1 h-10 w-full rounded-md border border-slate-200 px-3" value={single.duplicate_action} onChange={e=>setSingle({...single,duplicate_action:e.target.value})}><option value="skip">Skip high-confidence duplicates</option><option value="attach">Attach sources to existing</option><option value="create_anyway">Create separate draft anyway</option></select></label><div className="mt-5 flex flex-wrap gap-3"><Button disabled={busy||!single.name.trim()} className="bg-blue-700" onClick={()=>void run(()=>createSingleVerifiedImport(single),"Draft import created.")}>{busy?<RefreshCw className="mr-2 h-4 w-4 animate-spin"/>:<ShieldCheck className="mr-2 h-4 w-4"/>}Create Draft Import</Button><Button disabled={busy||!single.name.trim()} variant="outline" onClick={()=>void run(()=>createSingleVerifiedImport({...single,fetch_google:true}),"Draft created and enriched with available Google Places facts.")}>Create + Enrich with Google</Button><Button disabled={busy||!single.name.trim()} variant="outline" onClick={()=>void run(()=>createSingleVerifiedImport(single),"Draft and declared source links recorded.")}>Create + Add Sources</Button></div><p className="mt-3 text-xs text-slate-500">Google Places fills reviewable location facts. RERA, prices, amenities and editorial fields require declared sources or the review-only generators.</p></section>:null}

    {tab==="bulk"?<section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Bulk verified import</h2><p className="mt-1 text-sm text-slate-500">One society per line. Pipe, tab and comma delimiters are supported. Maximum 100.</p><textarea className="mt-4 min-h-64 w-full rounded-2xl border border-slate-200 p-4 font-mono text-sm" value={bulk} onChange={e=>setBulk(e.target.value)} placeholder={"DLF Alameda | Sector 73 | DLF\nDLF The Crest | Sector 54 | DLF\nM3M Golf Estate | Sector 65 | M3M"}/><Button disabled={busy||!bulk.trim()} className="mt-4 bg-blue-700" onClick={()=>void run(()=>createBulkVerifiedImport({items:bulk,default_city:"Gurugram",duplicate_action:"skip"}),"Bulk import processed.")}><ListChecks className="mr-2 h-4 w-4"/>Process Draft Rows</Button></section>:null}

    {tab==="excel"?<section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Excel / CSV import</h2><p className="mt-1 text-sm text-slate-500">Preview mapping first, then confirm up to 500 rows.</p></div><Button variant="outline" onClick={()=>void downloadVerifiedImportTemplate()}>Download sample template</Button></div><label className="mt-5 flex cursor-pointer items-center justify-center rounded-2xl border border-dashed border-blue-200 bg-blue-50 p-8 text-sm font-bold text-blue-700"><Upload className="mr-2 h-5 w-5"/>Choose .xlsx or .csv<input type="file" accept=".xlsx,.csv" className="hidden" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setFileName(f.name);await run(async()=>{const r=await previewVerifiedExcelImport(f);setPreview(r.data);return {message:`Previewed ${r.data.rows.length} rows.`};},"Preview ready.");}}/></label>{preview?<div className="mt-5"><p className="text-sm font-bold">Detected: {Object.keys(preview.mapping||{}).join(", ")}</p>{preview.warnings?.length?<p className="mt-2 text-sm text-amber-700">{preview.warnings.slice(0,5).join(" · ")}</p>:null}<div className="mt-3 max-h-64 overflow-auto rounded-2xl border"><table className="w-full text-left text-xs"><thead className="bg-slate-50"><tr><th className="p-3">Row</th><th>Name</th><th>Builder</th><th>Sector</th><th>Source</th></tr></thead><tbody>{preview.rows.slice(0,20).map((r:any)=><tr key={r.row_number} className="border-t"><td className="p-3">{r.row_number}</td><td>{r.name}</td><td>{r.builder_name}</td><td>{r.sector}</td><td>{r.source_type||"excel"}</td></tr>)}</tbody></table></div><Button disabled={busy} className="mt-4 bg-blue-700" onClick={()=>void run(()=>confirmVerifiedExcelImport({rows:preview.rows,file_name:fileName,duplicate_action:"skip"}),"Excel import completed.")}><CheckCircle2 className="mr-2 h-4 w-4"/>Confirm Draft Import</Button></div>:null}</section>:null}

    {tab==="jobs"?<section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex justify-between"><h2 className="text-xl font-black">Import jobs</h2><Button size="sm" variant="outline" onClick={()=>void loadJobs()}>Refresh</Button></div><div className="mt-4 overflow-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-400"><th className="p-3">Job</th><th>Type</th><th>Status</th><th>Rows</th><th>Created</th><th>Skipped</th><th>Failed</th><th>Confidence</th><th></th></tr></thead><tbody>{jobs.map(j=><tr key={j.id} className="border-b"><td className="p-3 font-bold">#{j.id}</td><td>{j.job_type}</td><td>{j.status}</td><td>{j.processed_rows}/{j.total_rows}</td><td>{j.created_societies_count}</td><td>{j.skipped_count}</td><td>{j.failed_count}</td><td><Confidence value={j.overall_confidence}/></td><td>{j.failed_count?<button className="font-bold text-blue-700" onClick={()=>void run(()=>retryVerifiedImportFailedRows(j.id),"Failed rows retried.")}>Retry</button>:"—"}</td></tr>)}</tbody></table></div></section>:null}

    {tab==="review"?<div className="space-y-5">{layerEditorPanel}<section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Societies needing review</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{review.societies.map(s=><div key={s.id} className="rounded-2xl border p-4"><div className="flex justify-between"><p className="font-black">{s.name}</p><Confidence value={s.overall_confidence}/></div><p className="mt-1 text-xs text-slate-500">{s.builder||"Builder missing"} · {s.sector||"Sector missing"} · {s.city}</p><p className="mt-2 text-xs font-semibold text-amber-700">{s.source_count} sources · {s.field_count} fields · {s.image_count} images pending</p><div className="mt-3 flex flex-wrap gap-3"><a className="text-xs font-bold text-blue-700" href={`/admin/societies/${s.id}/edit`}>Open Society Draft</a><button className="text-xs font-black text-emerald-700" onClick={()=>void run(()=>applyVerifiedHighConfidenceFields(s.id),"High-confidence fields applied.")}>Apply all high confidence fields</button></div>{renderLayerCards(s)}</div>)}</div></section>
      <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Fields needing approval</h2><div className="mt-4 space-y-2">{review.fields.slice(0,100).map(f=><div key={f.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-slate-50 p-3"><div><p className="text-sm font-bold">Society #{f.society_id} · {f.field_name}</p><p className="max-w-2xl truncate text-xs text-slate-500">{f.normalized_value} · {f.source_type}</p></div><div className="flex items-center gap-2"><Confidence value={f.confidence_score}/><button className="text-xs font-black text-emerald-700" onClick={()=>void run(()=>approveVerifiedImportField(f.id),"Field approved.")}>Approve</button><button className="text-xs font-black text-rose-700" onClick={()=>void run(()=>rejectVerifiedImportField(f.id),"Field rejected.")}>Reject</button></div></div>)}</div></section>
      <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Images needing approval</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{review.images.map(i=><VerifiedImportImageCard key={i.id} image={i} busy={busy} onCover={approveQueueCover} onGallery={(item)=>void run(()=>approveVerifiedImportImage(item.id),"Image approved to gallery.")} onReject={(item)=>void run(()=>rejectVerifiedImportImage(item.id),"Image rejected.")} draftHref={`/admin/societies/${i.society_id}/edit`}/>)}</div></section><section className="grid gap-5 md:grid-cols-2"><div className="rounded-[28px] border border-amber-200 bg-amber-50 p-6"><h2 className="font-black text-amber-900">Duplicate warnings</h2><p className="mt-2 text-sm text-amber-800">{review.duplicates.length} high-confidence duplicate rows are held back from creation.</p></div><div className="rounded-[28px] border border-rose-200 bg-rose-50 p-6"><h2 className="font-black text-rose-900">Low confidence imports</h2><p className="mt-2 text-sm text-rose-800">{review.low_confidence.length} rows need closer source review.</p></div></section></div>:null}
  </AdminLayout>;
}
