import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, BarChart3, CheckCircle2, FileText, Gauge, Globe2, KeyRound, Link2, ListChecks, RefreshCw, Search, Sparkles, Target, XCircle } from 'lucide-react';
import { AdminLayout } from '@/layouts/AdminLayout';
import { Button } from '@/components/ui/button';
import {
  approveSeoAutopilotDraft, fetchGoogleSearchConsole, fetchSeoAutopilotDashboard, fetchSeoAutopilotDrafts,
  fetchSeoAutopilotKeywords, fetchSeoAutopilotPages, fetchSeoAutopilotReports, fetchSeoAutopilotTasks,
  generateSeoAutopilotDraft, generateSeoAutopilotReport, rejectSeoAutopilotDraft, runSeoAutopilotAudit,
  seedSeoAutopilotKeywords, updateSeoAutopilotTask, publishSeoAutopilotDraft, updateSeoAutopilotDraft,
  fetchRevoicePending, approveRevoice, rejectRevoice, generateRevoiceBatch, runSeoAutopilotCycle,
  updateSeoAutopilotSettings,
} from '@/lib/seoAutopilotApi';

type Tab='overview'|'pages'|'tasks'|'keywords'|'drafts'|'revoice'|'reports';
type RevoiceItem={society_id:number;society_name?:string;society_slug?:string;generated_at?:string;live:Record<string,any>;draft:Record<string,any>};
type PageRow={id:number;page_type:string;url:string;title?:string;is_public:boolean;is_indexable:boolean;content_word_count:number;latest_audit?:{score:number;status:string;issues:any[]}};
type Task={id:number;priority:string;title:string;description?:string;task_type:string;page?:PageRow;source:string};
type Draft={id:number;status:string;confidence_score:number;reason?:string;current_version:any;suggested_version:any;data_sources?:string[];risk_warnings?:string[];page?:PageRow};
type MarketingPlan={id:string;title:string;outcome:string;cadence:string;automation:string[];kpis:string[]};
const tabs:Array<[Tab,string,any]>=[['overview','Command Center',Gauge],['pages','Page Audits',Globe2],['tasks','SEO Tasks',ListChecks],['keywords','Keywords',KeyRound],['drafts','AI Drafts',Sparkles],['revoice','Re-voice',Sparkles],['reports','Reports',BarChart3]];
const unwrap=(payload:any)=>payload?.data?.data||payload?.data||[];
const scoreTone=(score=0)=>score>=80?'bg-emerald-100 text-emerald-800':score>=50?'bg-amber-100 text-amber-800':'bg-rose-100 text-rose-800';
const priorityTone=(priority='medium')=>priority==='critical'||priority==='high'?'bg-rose-100 text-rose-800':priority==='medium'?'bg-amber-100 text-amber-800':'bg-blue-100 text-blue-800';

export function AdminSeoAutopilotPage(){
  const[tab,setTab]=useState<Tab>('overview');const[dashboard,setDashboard]=useState<any>(null);const[pages,setPages]=useState<PageRow[]>([]);const[tasks,setTasks]=useState<Task[]>([]);const[keywords,setKeywords]=useState<any[]>([]);const[drafts,setDrafts]=useState<Draft[]>([]);const[reports,setReports]=useState<any[]>([]);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');const[search,setSearch]=useState('');const[type,setType]=useState('');const[editing,setEditing]=useState<number|null>(null);const[editForm,setEditForm]=useState<Record<string,string>>({});const[revoice,setRevoice]=useState<RevoiceItem[]>([]);
  const load=useCallback(async()=>{setError('');try{const[d,p,t,k,dr,r]=await Promise.all([fetchSeoAutopilotDashboard(),fetchSeoAutopilotPages('per_page=100'),fetchSeoAutopilotTasks(),fetchSeoAutopilotKeywords(),fetchSeoAutopilotDrafts(),fetchSeoAutopilotReports()]);setDashboard(d.data);setPages(unwrap(p));setTasks(unwrap(t));setKeywords(unwrap(k));setDrafts(unwrap(dr));setReports(unwrap(r));try{setRevoice(unwrap(await fetchRevoicePending()));}catch{/* revoice queue is optional */}}catch(e){setError(e instanceof Error?e.message:'Could not load SEO Autopilot.');}},[]);
  useEffect(()=>{void load()},[load]);
  const run=async(key:string,action:()=>Promise<any>)=>{try{setBusy(key);setError('');setNotice('');const result=await action();setNotice(result?.message||'SEO action completed.');await load();}catch(e){setError(e instanceof Error?e.message:'SEO action failed.');}finally{setBusy('');}};
  const updateAutomation=(key:string,value:boolean|number|string)=>run(`automation-${key}`,()=>updateSeoAutopilotSettings({[key]:value}));
  const startEdit=(draft:Draft)=>{const value=draft.suggested_version||{};setEditing(draft.id);setEditForm({seo_title:value.seo_title||'',seo_description:value.seo_description||'',seo_h1:value.seo_h1||'',intro_summary:value.intro_summary||'',reason:draft.reason||''});};
  const summary=dashboard?.summary||{};const filteredPages=pages.filter(p=>(!type||p.page_type===type)&&(!search||`${p.url} ${p.title||''}`.toLowerCase().includes(search.toLowerCase())));
  return <AdminLayout title="SEO Autopilot" subtitle="Audit, improve and monitor every indexable SocietyFlats page — AI remains review-only.">
    <div className="mb-5 flex flex-wrap gap-2">{['No AI auto-publish','Verified facts only','Admin approval logged'].map(x=><span key={x} className="rounded-full border border-blue-100 bg-blue-50 px-3 py-1.5 text-xs font-black text-blue-700">{x}</span>)}</div>
    {notice?<div className="mb-4 rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{notice}</div>:null}{error?<div className="mb-4 flex gap-2 rounded-2xl bg-rose-50 p-4 text-sm font-bold text-rose-800"><AlertTriangle className="h-4 w-4"/>{error}</div>:null}
    <div className="mb-6 flex gap-2 overflow-x-auto rounded-[22px] border border-slate-200 bg-white p-2">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-2xl px-4 py-2.5 text-sm font-black ${tab===id?'bg-slate-950 text-white':'text-slate-600 hover:bg-slate-50'}`}><Icon className="h-4 w-4"/>{label}</button>)}</div>
    {!dashboard?<div className="rounded-[28px] border bg-white p-10 text-center"><RefreshCw className="mx-auto h-6 w-6 animate-spin text-blue-600"/><p className="mt-3 font-bold text-slate-600">Building the SEO page inventory…</p></div>:null}

    {dashboard&&tab==='overview'?<div className="space-y-6">
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[
        ['Public pages',summary.public_pages,Globe2],['Average score',summary.average_score,Gauge],['Open tasks',summary.open_tasks,ListChecks],['Pending drafts',summary.pending_drafts,Sparkles],['Failed checks',summary.failed_checks,AlertTriangle],
      ].map(([label,value,Icon]:any)=><article key={label} className="rounded-[22px] border border-slate-200 bg-white p-5 shadow-sm"><Icon className="h-5 w-5 text-blue-700"/><p className="mt-4 text-3xl font-black text-slate-950">{value??0}</p><p className="mt-1 text-sm font-bold text-slate-500">{label}</p></article>)}</section>
      <section className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]">
        <article className="rounded-[28px] border border-blue-100 bg-gradient-to-br from-blue-950 via-slate-950 to-slate-900 p-6 text-white shadow-sm">
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div>
              <p className="text-xs font-black uppercase tracking-[0.22em] text-blue-200">Automation engine</p>
              <h2 className="mt-2 text-2xl font-black">{dashboard.automation?.settings?.enabled?'Running daily':'Paused'}</h2>
              <p className="mt-2 max-w-xl text-sm text-slate-300">Runs audits, Search Console import, keyword refresh, opportunity scoring, review-only AI drafts and reports with one scheduled cycle.</p>
            </div>
            <Button disabled={Boolean(busy)} onClick={()=>void run('cycle',runSeoAutopilotCycle)} className="bg-white text-slate-950 hover:bg-blue-50"><RefreshCw className={`mr-2 h-4 w-4 ${busy==='cycle'?'animate-spin':''}`}/>Run complete automation</Button>
          </div>
          <div className="mt-5 grid gap-3 sm:grid-cols-3">
            <div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-slate-300">Next run</p><p className="mt-1 text-sm font-black">{dashboard.automation?.next_run_at?new Date(dashboard.automation.next_run_at).toLocaleString():'—'}</p></div>
            <div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-slate-300">Last run</p><p className="mt-1 text-sm font-black">{dashboard.automation?.last_run?.status||'No run yet'}</p></div>
            <div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-slate-300">Drafts per run</p><select disabled={Boolean(busy)} value={dashboard.automation?.settings?.drafts_per_run??5} onChange={e=>void updateAutomation('drafts_per_run',Number(e.target.value))} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 p-2 text-sm font-black text-white"><option value={0}>0</option><option value={3}>3</option><option value={5}>5</option><option value={10}>10</option><option value={20}>20</option></select></div>
          </div>
          <div className="mt-5 grid gap-2 sm:grid-cols-2">
            {[
              ['enabled','Autopilot enabled'],['audit_enabled','Page audits'],['technical_checks_enabled','Technical checks'],['search_console_enabled','Search Console import'],['keyword_refresh_enabled','Keyword refresh'],['draft_generation_enabled','Review draft generation'],['auto_publish_enabled','Auto-publish safe drafts'],['reports_enabled','Reports'],
            ].map(([key,label])=><label key={key} className="flex items-center justify-between gap-3 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-bold"><span>{label}</span><input type="checkbox" checked={Boolean(dashboard.automation?.settings?.[key])} disabled={Boolean(busy)} onChange={e=>void updateAutomation(key,e.target.checked)} className="h-5 w-5 accent-blue-500"/></label>)}
          </div>
          {dashboard.automation?.recent_runs?.length?<div className="mt-5 rounded-2xl bg-white/5 p-4"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-200">Recent runs</p><div className="mt-3 space-y-2">{dashboard.automation.recent_runs.slice(0,4).map((run:any)=><div key={run.id} className="flex items-center justify-between gap-3 text-xs"><span className="font-bold">#{run.id} · {run.trigger}</span><span className="text-slate-300">{run.status} · {run.summary?.drafts_generated??0} drafts</span></div>)}</div></div>:null}
        </article>
        <article className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-start justify-between gap-4">
            <div><p className="text-xs font-black uppercase tracking-[0.22em] text-blue-700">SEO marketing plan</p><h2 className="mt-2 text-2xl font-black text-slate-950">From crawl health to organic leads</h2><p className="mt-2 text-sm text-slate-500">The plan is now embedded in Autopilot so the daily cycle has a clear business path, not just a checklist.</p></div>
          </div>
          <div className="mt-5 grid gap-3 lg:grid-cols-2">{(dashboard.marketing_plan||[]).map((phase:MarketingPlan)=><div key={phase.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-black text-slate-950">{phase.title}</h3><span className="rounded-full bg-white px-2.5 py-1 text-[11px] font-black text-blue-700">{phase.cadence}</span></div><p className="mt-2 text-sm text-slate-600">{phase.outcome}</p><p className="mt-3 text-[11px] font-black uppercase tracking-[0.12em] text-slate-400">Automation</p><ul className="mt-2 space-y-1 text-xs font-bold text-slate-600">{phase.automation.map(item=><li key={item}>• {item}</li>)}</ul></div>)}</div>
        </article>
      </section>
      <section className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-[28px] border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Top opportunities</h2><p className="text-sm text-slate-500">Prioritized from audits and Search Console.</p></div><Button disabled={Boolean(busy)} onClick={()=>void run('audit',()=>runSeoAutopilotAudit())}><RefreshCw className={`mr-2 h-4 w-4 ${busy==='audit'?'animate-spin':''}`}/>Run full audit</Button></div><div className="mt-5 space-y-3">{(dashboard.opportunities||[]).slice(0,8).map((task:Task)=><div key={task.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-black text-slate-900">{task.title}</p><p className="mt-1 text-xs text-slate-500">{task.page?.url||'Site-wide'} · {task.source}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-black uppercase ${priorityTone(task.priority)}`}>{task.priority}</span></div></div>)}</div></div>
        <div className="rounded-[28px] bg-slate-950 p-6 text-white"><h2 className="text-xl font-black">Search Console</h2><p className="mt-2 text-sm text-slate-300">{dashboard.search_console?.configured?'Connected and ready for scheduled imports.':'Optional integration is not configured. Manual audits still run normally.'}</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-4"><p className="text-2xl font-black">{dashboard.search_console?.clicks_28d||0}</p><p className="text-xs text-slate-300">Clicks · 28d</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-2xl font-black">{dashboard.search_console?.impressions_28d||0}</p><p className="text-xs text-slate-300">Impressions · 28d</p></div></div><Button variant="outline" className="mt-4 w-full border-white/20 bg-white/5 text-white hover:bg-white/10" disabled={Boolean(busy)} onClick={()=>void run('gsc',fetchGoogleSearchConsole)}>Import now</Button></div>
      </section>
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Missing title',summary.missing_title],['Missing meta',summary.missing_meta],['Thin content',summary.thin_content],['Missing internal links',summary.missing_internal_links],['Duplicate titles',summary.duplicate_titles],['Duplicate meta',summary.duplicate_meta],['Missing H1',summary.missing_h1],['Public missing sitemap',dashboard.sitemap?.public_not_in_sitemap]].map(([label,value])=><div key={String(label)} className="rounded-2xl border bg-white p-4"><p className="text-2xl font-black">{value||0}</p><p className="text-sm text-slate-500">{label}</p></div>)}</section>
    </div>:null}

    {dashboard&&tab==='pages'?<section className="rounded-[28px] border border-slate-200 bg-white p-5"><div className="flex flex-wrap gap-3"><label className="flex min-w-[240px] flex-1 items-center gap-2 rounded-xl border px-3"><Search className="h-4 w-4 text-slate-400"/><input className="h-11 min-w-0 flex-1 outline-none" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filter URL or title"/></label><select value={type} onChange={e=>setType(e.target.value)} className="h-11 rounded-xl border px-3"><option value="">All page types</option>{Array.from(new Set(pages.map(p=>p.page_type))).map(v=><option key={v}>{v}</option>)}</select></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="p-3">Page</th><th>Type</th><th>Score</th><th>Words</th><th>Index</th><th>Actions</th></tr></thead><tbody>{filteredPages.map(page=><tr key={page.id} className="border-b last:border-0"><td className="p-3"><p className="font-black">{page.title||'Missing title'}</p><p className="text-xs text-slate-500">{page.url}</p></td><td className="capitalize">{page.page_type}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-black ${scoreTone(page.latest_audit?.score)}`}>{page.latest_audit?.score??'—'}</span></td><td>{page.content_word_count}</td><td>{page.is_public&&page.is_indexable?<CheckCircle2 className="h-4 w-4 text-emerald-600"/>:<XCircle className="h-4 w-4 text-slate-400"/>}</td><td><div className="flex gap-2"><button className="text-xs font-black text-blue-700" onClick={()=>void run(`audit-${page.id}`,()=>runSeoAutopilotAudit(page.id))}>Audit</button><button className="text-xs font-black text-violet-700" onClick={()=>void run(`draft-${page.id}`,()=>generateSeoAutopilotDraft(page.id))}>Draft</button></div></td></tr>)}</tbody></table></div></section>:null}

    {dashboard&&tab==='tasks'?<section className="space-y-3">{tasks.length?tasks.map(task=><article key={task.id} className="rounded-[22px] border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] font-black uppercase ${priorityTone(task.priority)}`}>{task.priority}</span><span className="text-xs font-bold text-slate-400">{task.source}</span></div><h3 className="mt-3 font-black">{task.title}</h3><p className="mt-1 text-sm text-slate-600">{task.description}</p><p className="mt-2 text-xs text-blue-700">{task.page?.url||'Site-wide task'}</p></div><Button variant="outline" disabled={Boolean(busy)} onClick={()=>void run(`task-${task.id}`,()=>updateSeoAutopilotTask(task.id,'resolved'))}>Mark resolved</Button></div></article>):<div className="rounded-[28px] bg-emerald-50 p-8 text-center font-black text-emerald-800">No open SEO tasks.</div>}</section>:null}

    {dashboard&&tab==='keywords'?<section className="rounded-[28px] border bg-white p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">Keyword intelligence</h2><p className="text-sm text-slate-500">First-party clusters mapped to existing pages; difficulty stays blank until a trusted source is connected.</p></div><Button onClick={()=>void run('keywords',seedSeoAutopilotKeywords)} disabled={Boolean(busy)}>Refresh clusters</Button></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{keywords.map(k=><article key={k.id} className="rounded-2xl border p-4"><div className="flex justify-between gap-2"><p className="font-black">{k.keyword}</p><span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-black uppercase text-blue-700">{k.cluster_type}</span></div><p className="mt-2 text-xs text-slate-500">Intent: {k.intent||'unclassified'}</p><p className="mt-1 truncate text-xs text-blue-700">{k.page?.url||k.suggested_url||'Suggested page needed'}</p></article>)}</div></section>:null}

    {dashboard&&tab==='drafts'?<section className="space-y-4">{drafts.length?drafts.map(draft=><article key={draft.id} className="rounded-[28px] border bg-white p-6">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex gap-2"><span className="rounded-full bg-violet-100 px-2.5 py-1 text-xs font-black text-violet-800">{draft.status}</span><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-black text-blue-700">{draft.confidence_score}% confidence</span></div><h3 className="mt-3 text-lg font-black">{draft.page?.title||draft.page?.url}</h3><p className="text-sm text-slate-500">{draft.reason}</p></div>{draft.status==='needs_review'?<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>startEdit(draft)}>Edit</Button><Button onClick={()=>void run(`approve-${draft.id}`,()=>approveSeoAutopilotDraft(draft.id))}>Approve</Button><Button variant="outline" className="text-rose-700" onClick={()=>void run(`reject-${draft.id}`,()=>rejectSeoAutopilotDraft(draft.id,'Rejected during admin review.'))}>Reject</Button></div>:null}</div>
      {editing===draft.id?<div className="mt-5 rounded-2xl border border-violet-200 bg-violet-50 p-4"><p className="text-sm font-black text-violet-950">Edit review draft</p><div className="mt-3 grid gap-3 lg:grid-cols-2"><input className="rounded-xl border bg-white p-3 text-sm" value={editForm.seo_title||''} onChange={e=>setEditForm({...editForm,seo_title:e.target.value})} placeholder="SEO title"/><input className="rounded-xl border bg-white p-3 text-sm" value={editForm.seo_h1||''} onChange={e=>setEditForm({...editForm,seo_h1:e.target.value})} placeholder="H1"/><textarea className="rounded-xl border bg-white p-3 text-sm lg:col-span-2" value={editForm.seo_description||''} onChange={e=>setEditForm({...editForm,seo_description:e.target.value})} placeholder="Meta description"/><textarea className="rounded-xl border bg-white p-3 text-sm lg:col-span-2" value={editForm.intro_summary||''} onChange={e=>setEditForm({...editForm,intro_summary:e.target.value})} placeholder="Intro summary"/></div><div className="mt-3 flex gap-2"><Button disabled={Boolean(busy)} onClick={()=>void run(`edit-${draft.id}`,async()=>{const result=await updateSeoAutopilotDraft(draft.id,editForm);setEditing(null);return result})}>Save draft</Button><Button variant="outline" onClick={()=>setEditing(null)}>Cancel</Button></div></div>:null}
      <div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase text-slate-500">Current</p><pre className="mt-2 whitespace-pre-wrap text-xs">{JSON.stringify(draft.current_version,null,2)}</pre></div><div className="rounded-2xl bg-blue-50 p-4"><p className="text-xs font-black uppercase text-blue-700">Suggested</p><pre className="mt-2 whitespace-pre-wrap text-xs">{JSON.stringify(draft.suggested_version,null,2)}</pre></div></div>{draft.risk_warnings?.length?<div className="mt-4 rounded-2xl bg-amber-50 p-4 text-xs font-bold text-amber-800">{draft.risk_warnings.join(' · ')}</div>:null}
    </article>):<div className="rounded-[28px] border bg-white p-8 text-center text-slate-500">No SEO drafts yet. Generate one from Page Audits.</div>}</section>:null}

    {dashboard&&tab==='revoice'?<section className="space-y-4">
      <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-amber-900"><span className="font-black">Review-first re-voice.</span> These published societies have a re-worded draft in the current brand voice. The live page keeps its existing copy until you approve — approving swaps the new copy in; rejecting discards it.</p><div className="flex shrink-0 gap-2"><Button disabled={Boolean(busy)} onClick={()=>void run('revoice-gen-5',()=>generateRevoiceBatch(5))}><Sparkles className={`mr-2 h-4 w-4 ${busy==='revoice-gen-5'?'animate-spin':''}`}/>Re-voice next 5</Button><Button variant="outline" disabled={Boolean(busy)} onClick={()=>void run('revoice-gen-20',()=>generateRevoiceBatch(20))}>Next 20</Button></div></div></div>
      {revoice.length?revoice.map(item=>{const fields:Array<[string,string]>=[['seo_title','Title'],['seo_h1','H1'],['seo_description','Meta description'],['intro_summary','Intro']];return(
      <article key={item.society_id} className="rounded-[24px] border border-slate-200 bg-white p-5">
        <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-black text-slate-950">{item.society_name}</h3><p className="text-xs text-slate-500">Draft generated {item.generated_at?new Date(item.generated_at).toLocaleString():'recently'} · live copy unchanged</p></div><div className="flex gap-2"><Button className="bg-emerald-700 hover:bg-emerald-800" disabled={Boolean(busy)} onClick={()=>void run(`revoice-approve-${item.society_id}`,()=>approveRevoice(item.society_id))}>Approve &amp; publish</Button><Button variant="outline" className="text-rose-700" disabled={Boolean(busy)} onClick={()=>void run(`revoice-reject-${item.society_id}`,()=>rejectRevoice(item.society_id))}>Reject</Button></div></div>
        <div className="mt-4 space-y-3">{fields.map(([key,label])=>(<div key={key} className="grid gap-3 lg:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-3"><p className="text-[11px] font-black uppercase text-slate-500">{label} · live</p><p className="mt-1 text-sm text-slate-700">{String(item.live?.[key]||'—')}</p></div><div className="rounded-2xl bg-blue-50 p-3"><p className="text-[11px] font-black uppercase text-blue-700">{label} · re-voiced</p><p className="mt-1 text-sm text-slate-900">{String(item.draft?.[key]||'—')}</p></div></div>))}</div>
      </article>);}):<div className="rounded-[28px] border bg-white p-8 text-center text-slate-500">No pending re-voice drafts. Run <span className="font-mono text-xs">php artisan seo:revoice</span> to generate a batch.</div>}
    </section>:null}

    {dashboard&&tab==='reports'?<section className="space-y-5"><div className="flex flex-wrap gap-2">{['daily','weekly','monthly'].map(period=><Button key={period} variant="outline" onClick={()=>void run(`report-${period}`,()=>generateSeoAutopilotReport(period))} disabled={Boolean(busy)} className="capitalize"><FileText className="mr-2 h-4 w-4"/>Generate {period}</Button>)}</div><div className="grid gap-4 xl:grid-cols-2">{reports.map(report=><article key={report.id} className="rounded-[24px] border bg-white p-5"><div className="flex items-center justify-between"><h3 className="text-lg font-black capitalize">{report.period} report</h3><span className="text-xs text-slate-500">{report.period_start} → {report.period_end}</span></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Pages',report.summary.pages],['Avg score',report.summary.average_score],['Open tasks',report.summary.open_tasks],['Drafts',report.summary.pending_drafts]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-slate-50 p-3"><p className="text-xl font-black">{value||0}</p><p className="text-xs text-slate-500">{label}</p></div>)}</div></article>)}</div></section>:null}
    {dashboard&&tab==='drafts'&&drafts.some(draft=>draft.status==='approved')?<section className="mt-5 rounded-[24px] border border-emerald-200 bg-emerald-50 p-5"><h2 className="font-black text-emerald-950">Approved drafts ready for explicit publication</h2><p className="mt-1 text-sm text-emerald-800">Approval never publishes automatically. Publish only after reviewing the before/after cards above.</p><div className="mt-4 flex flex-wrap gap-2">{drafts.filter(draft=>draft.status==='approved').map(draft=><Button key={draft.id} className="bg-emerald-700 hover:bg-emerald-800" onClick={()=>void run(`publish-${draft.id}`,()=>publishSeoAutopilotDraft(draft.id))}>Publish {draft.page?.url||`draft #${draft.id}`}</Button>)}</div></section>:null}
    {dashboard&&tab==='drafts'&&drafts.length?<section className="mt-4 flex flex-wrap gap-2">{drafts.filter(draft=>draft.page&&draft.status!=='published').slice(0,12).map(draft=><Button key={`regen-${draft.id}`} variant="outline" onClick={()=>draft.page&&void run(`regenerate-${draft.id}`,()=>generateSeoAutopilotDraft(draft.page.id))}>Regenerate {draft.page?.url}</Button>)}</section>:null}
  </AdminLayout>;
}
