import { useEffect, useState } from "react";
import { Globe2, RefreshCw } from "lucide-react";
import { AdminLayout } from "@/layouts/AdminLayout";
import { Button } from "@/components/ui/button";
import { adminFetch } from "@/lib/adminApi";

type NriCase = { id: number; name: string; country: string; contact_method: string; phone?: string; email?: string; service_type: string; property_context?: string; notes?: string; status: string; assigned_to?: string };

export function AdminNriCasesPage() {
  const [items, setItems] = useState<NriCase[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { try { setLoading(true); const response = await adminFetch("/admin/nri-cases?per_page=100"); const json = await response.json().catch(() => ({})); if (!response.ok) throw new Error(json?.message || "Could not load NRI cases."); setItems(json?.data?.data || []); } catch (err) { setError(err instanceof Error ? err.message : "Could not load NRI cases."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function update(item: NriCase, status: string) { const response = await adminFetch(`/admin/nri-cases/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const json = await response.json().catch(() => ({})); if (!response.ok) { setError(json?.message || "Could not update case."); return; } setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, ...json.data } : entry)); }
  return <AdminLayout title="NRI Cases" subtitle="Private overseas consultation intake and follow-up queue."><div className="mb-5 flex items-center justify-between rounded-[24px] border border-blue-100 bg-blue-50 p-4"><p className="flex items-center gap-2 text-sm font-semibold text-blue-800"><Globe2 className="h-5 w-5" />Keep legal, tax, FEMA and remittance advice outside SocietyFlats scope.</p><Button size="sm" variant="outline" onClick={() => void load()}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh</Button></div>{error ? <p className="mb-4 rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</p> : null}<div className="space-y-3">{items.map((item) => <article key={item.id} className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-4 lg:grid-cols-[1.5fr_1fr]"><div><p className="font-black text-slate-950">{item.name} · {item.country}</p><p className="mt-1 text-xs text-slate-500">{item.service_type} · {item.contact_method}: {item.contact_method === 'email' ? item.email : item.phone}</p>{item.property_context ? <p className="mt-2 text-sm text-slate-700">{item.property_context}</p> : null}{item.notes ? <p className="mt-2 text-xs leading-5 text-slate-500">{item.notes}</p> : null}</div><select value={item.status} onChange={(e) => void update(item, e.target.value)} className="h-10 rounded-xl border border-slate-200 px-3 text-sm">{['submitted','contacted','documents_pending','in_review','completed','closed'].map((value) => <option key={value} value={value}>{value}</option>)}</select></div></article>)}{!loading && !items.length ? <div className="rounded-[24px] border border-dashed border-slate-200 bg-white p-10 text-center text-sm text-slate-500">No NRI cases yet.</div> : null}</div></AdminLayout>;
}
