<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\SavedSearch;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

/**
 * Recording what someone asked for, without asking who they are.
 *
 * Nine deliberate answers about budget, size, area, commute and the things no filter can
 * express is the best demand signal this site collects — and until now it only survived if
 * the person signed in to save it. Everyone else's brief lived in one browser and died with
 * the tab, which left the demand-gap report reading leads and little else.
 *
 * Nothing here identifies anybody: no name, no phone, no email, no account. The token is
 * random, generated by the browser, and exists only so that editing a brief updates the
 * same row rather than filling the table with one person changing their mind six times.
 */
class BriefController extends Controller
{
    public function store(Request $request): JsonResponse
    {
        $data = $request->validate([
            'token' => ['required', 'string', 'min:16', 'max:64', 'alpha_dash'],
            'filters' => ['required', 'array'],
            'filters.mode' => ['nullable', 'string', 'max:20'],
            'filters.where' => ['nullable', 'string', 'max:120'],
            'filters.commute' => ['nullable', 'string', 'max:120'],
            'filters.city' => ['nullable', 'string', 'max:60'],
            'filters.bhk' => ['nullable', 'string', 'max:40'],
            'filters.budget' => ['nullable', 'string', 'max:20'],
            'filters.purpose' => ['nullable', 'string', 'max:60'],
            'filters.timeline' => ['nullable', 'string', 'max:40'],
            'filters.priorities' => ['nullable', 'string', 'max:200'],
            // Their own words, which is often the only place a real requirement appears.
            'filters.notes' => ['nullable', 'string', 'max:1000'],
            'shortlisted' => ['nullable', 'integer', 'min:0', 'max:999'],
            'scanned' => ['nullable', 'integer', 'min:0', 'max:9999'],
        ]);

        $filters = array_merge(
            collect($data['filters'])->only([
                'mode', 'where', 'commute', 'city', 'bhk', 'budget',
                'purpose', 'timeline', 'priorities', 'notes',
            ])->map(fn ($value) => is_string($value) ? trim($value) : $value)->all(),
            [
                'kind' => 'brief',
                'shortlisted' => (int) ($data['shortlisted'] ?? 0),
                'scanned' => (int) ($data['scanned'] ?? 0),
            ],
        );

        // A brief with nothing in it is somebody who opened the page, not demand.
        if (! $this->worthRecording($filters)) {
            return response()->json(['status' => 'ok', 'recorded' => false]);
        }

        $brief = SavedSearch::updateOrCreate(
            ['anon_token' => $data['token']],
            [
                'account_id' => null,
                'name' => Str::limit('Brief · '.($filters['where'] ?: $filters['city'] ?: 'Delhi NCR'), 60, ''),
                'filters' => $filters,
                // Alerts need somewhere to send them. The matcher already skips anything
                // without an active account, so this is belt and braces.
                'alert_enabled' => false,
                'alert_channel' => 'whatsapp',
                'alert_frequency' => 'daily',
            ],
        );

        return response()->json(['status' => 'ok', 'recorded' => true, 'id' => $brief->id]);
    }

    /** Enough answered that it says something about what a real person wants. */
    private function worthRecording(array $filters): bool
    {
        $stated = collect(['where', 'commute', 'bhk', 'purpose', 'notes'])
            ->filter(fn (string $key) => filled($filters[$key] ?? null))
            ->count();

        return $stated >= 2;
    }
}
